version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    depends_on:
      - db
    command: flask run --host=0.0.0.0
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: flask_practice
      MYSQL_ROOT_PASSWORD: atul123  
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
